### ISSUE TITLE
Querying for split cards in active mode returns incorrect or no card image

### ISSUE THREAD

**Issue by henges** [OliverHofkens/scryfall-telegram-rs-serverless#11]
Hi, I hope you're well.

My group and I have noticed that querying for either half of a split card currently doesn't work in active mode. The bot will either return nothing or return an incorrect card image. For instance, neither [[Commit]], [[Memory]], nor [[Commit // Memory]] will return [Commit // Memory](https://scryfall.com/card/akh/211/commit-memory). The same goes for cards that have an Adventure; neither [[Stomp]] nor [[Bonecrusher Giant]] will return [Bonecrusher Giant](https://scryfall.com/card/eld/115/bonecrusher-giant-stomp). Presumably this is an issue with a single card face having multiple names.

The expected behaviour is that querying for either half of the card would return an image of the entire card face, assuming that the query text is closer to one of the split card names than it is to any other card name. Similarly, querying [[Commit memory]] or [[Commit // Memory]] would return the entire card.

Thank you as always for your wonderful bot!

**Comment by OliverHofkens** [comment]
Hi! Thanks for the kind words and for reporting this issue.
I've confirmed the issue you're reporting, well found!

It seems that this issue arises because split cards have a `card_faces` property, which we normally use only for double-faced cards. So the bot tries to find an image for the "split" you request in `card_faces`, but it doesn't exist because the card only has a single face.

I'll try to fix it this weekend!

**Comment by OliverHofkens** [comment]
I have a fix ready, which can be tested on the beta bot ([ScryfallBetaBot](https://t.me/ScryfallBetaBot))! 

![Screenshot 2021-02-05 at 15 40 38](https://user-images.githubusercontent.com/23633993/107047787-80fb3900-67c8-11eb-8bd8-409ae1ea131e.png)

If all goes well, I'll merge this into to the main bot tomorrow.
