### ISSUE TITLE
Get specific versions of a card from the same set

### ISSUE THREAD

**Issue by suroh1994** [OliverHofkens/scryfall-telegram-rs-serverless#16]
Hey,

I just ran into an issue which I couldn't solve with the current feature set. I wanted to post [a card](https://scryfall.com/card/vow/150/change-of-fortune) in a group, for which right now only the spanish version is available on Scryfall. BUT the [borderless version](https://scryfall.com/card/vow/375/change-of-fortune) is in english, so I wanted to post that one. However, because they are from the same set, using the `| SET` syntax does not work. 

Would it be possible to implement some kind of syntax, which allows the user to choose a specific version? Maybe have some kind of index, like `[[Change of Fortune | VOW | 2]]` and have the bot choose the second result from a returned list (not 100% sure how the Scryfall API returns results in this case). Or have the option to provide the exact set number? `[[VOW#375]]`

**Comment by OliverHofkens** [comment]
Hey,

This is a great feature request now that more and more alternative art and frame treatments are included in each set!

I'm not sure what the best way to implement this would be.
At the moment (due to an implementation detail), you can pass arbitrary Scryfall queries in between `[[ ]]` and the bot will return the first result.  So your specific case should already work like this: `[[ s:VOW cn:375 ]]` (set = vow, collector number = 375).
Maybe it's time to make this an explicit feature instead of an accident. That would expose a whole bunch of cool new cases, because the Scryfall query syntax is so expansive.

**Comment by OliverHofkens** [comment]
I have a small prototype of an elegant fix on the beta bot (see the attached movie). 
Basically, if you look up a single card, the bot will add a "Not what you meant?" button below the message.
Clicking that will offer a list of suggestions that you can click trough. The set is indicated, and an 🎨 emoji indicates that it's a special frame or artwork edition. Clicking a result will replace the bot's original image.


https://user-images.githubusercontent.com/23633993/147575995-188cf832-8d51-4dc4-8b54-903164b5a896.mov

**Comment by OliverHofkens** [comment]
This is now live since #17 is merged 🚀

**Comment by suroh1994** [comment]
Really good solution, I like it a lot. It also makes incomplete searches more usable. Now I can look up a card by only knowing a subset of its name and going through the results.
